<a href="https://colab.research.google.com/github/aryamanpathak2022/Cnn_models/blob/main/dogs_and_cats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install nngen


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 12.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 23.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.4/136.4 kB 12.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 5.1 MB/s eta 0:00:00
  Created wheel for nngen: filename=nngen-1.3.4-py3-none-any.whl size=161244 sha256=1a6be3982f2990c9ee203cd140b10b4629bce41f72bff9c51ce33c15c16e0825
  Stored in directory: /root/.cache/pip/wheels/0e/d8/4e/467100ae7a360fca7893d9007326f763acd15a42bef445ff80
  Created wheel for veriloggen: filename=veriloggen-2.3.0-py3-none-any.whl size=226044 sha256=76dc6c7d9398185583ff3e39899aedaab9ed8961dd0d671b9a8cd7986262b1fe
  Stored in directory: /root/.cache/pip/wheels/3f/e5/a8/416c

In [ ]:
import nngen as ng
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [ ]:
!nvidia-smi

Fri Jun 21 17:41:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
def filter_d_c(dataset):
  index=[i for i,target in enumerate(dataset.targets) if target in [3,5]]
  data=[dataset.data[i] for i in index]
  target=[0 if dataset.targets[i] ==3 else 1 for i in index  ]
  return data,target

In [ ]:


transform = transforms.Compose([
    transforms.Resize((32, 32)),  # Resize images
    transforms.ToTensor(),         # PyTorch tensors
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  # Normalize pixel values  and what
])

train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

avg= train_dataset.data

train_dataset.data,train_dataset.targets = filter_d_c(train_dataset)
test_dataset.data,test_dataset.targets = filter_d_c(test_dataset)

print(len(train_dataset.data))
print(len(test_dataset.data))





100%|██████████| 170498071/170498071 [00:03<00:00, 53892490.29it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified
10000
2000


In [ ]:
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)




In [ ]:
it=iter(train_loader)

In [ ]:
data = next(it)
img , label = data
# print(img.shape, label.shape)
# print(label[0:5])
print(img[0,0],img[0,0].shape)
print(torch.mean(img[:,0,:,:]))
data[0].shape



tensor([[-0.5059, -0.5059, -0.5294,  ..., -0.5137, -0.4667, -0.4667],
        [-0.4824, -0.4745, -0.4353,  ..., -0.5216, -0.4980, -0.5059],
        [-0.4510, -0.4745, -0.2627,  ..., -0.4588, -0.5216, -0.5059],
        ...,
        [-0.5451, -0.6000, -0.6314,  ..., -0.6157, -0.5922, -0.5608],
        [-0.5529, -0.5686, -0.5922,  ..., -0.6157, -0.6157, -0.5373],
        [-0.5843, -0.5216, -0.5373,  ..., -0.4980, -0.5294, -0.4196]]) torch.Size([32, 32])
tensor(-0.0324)


torch.Size([64, 3, 32, 32])

In [ ]:
data[0].shape


torch.Size([64, 3, 32, 32])

In [ ]:
data[0][:,1].mean([0,1]).shape,data[0][:,1].mean([0,1]),data[0][1].shape,data[0].mean([0,2,3])

(torch.Size([32]),
 tensor([-0.0863, -0.1061, -0.1103, -0.1118, -0.1220, -0.1266, -0.1162, -0.1110,
         -0.1008, -0.0843, -0.0892, -0.0933, -0.0737, -0.0468, -0.0314, -0.0272,
         -0.0131, -0.0028,  0.0059,  0.0027, -0.0157, -0.0373, -0.0482, -0.0459,
         -0.0444, -0.0450, -0.0446, -0.0460, -0.0440, -0.0529, -0.0625, -0.0664]),
 torch.Size([3, 32, 32]),
 tensor([-0.0324, -0.0624, -0.1604]))

In [ ]:
data[0].mean([0,2,3])

tensor([-0.0324, -0.0624, -0.1604])

In [ ]:
class cnn_network(nn.Module):
  def __init__(self):
        super(cnn_network, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, 3, padding=1)
        self.conv2 = nn.Conv2d(16, 32, 3, padding=1)
        self.conv3 = nn.Conv2d(32, 64, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(64*4*4, 512)
        self.fc2 = nn.Linear(512, 2)
#
  def forward(self, x):
    x = self.pool(torch.relu(self.conv1(x))) #out = 64*16*16*16
    #print(x.shape)
    x = self.pool(torch.relu(self.conv2(x))) #out = 64*32*8*8
    #print(x.shape)
    x = self.pool(torch.relu(self.conv3(x))) #out = 64*64*4*4
    #print(x.shape)
    x = x.view(-1,64*4*4) #what
    #print(x.shape)
    x = torch.relu(self.fc1(x))

    #print(x.shape)
    x = self.fc2(x)
    #print(x.shape)
    return x


In [ ]:
model=cnn_network()
data[0].shape

torch.Size([64, 3, 32, 32])

In [ ]:





#loss function and optimizer
criterion = nn.CrossEntropyLoss() #what
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)

for i in range(5):
  total_loss=0.00
  for j, data in enumerate(train_loader): #what
    inputs, labels = data
    optimizer.zero_grad()
    outputs = model(inputs)
    #print(outputs.shape,inputs.shape)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    # total_loss += loss.item()

print("completed training")

#training completed





completed training


In [ ]:
correct = 0
total = 0

with torch.no_grad():
    for data in test_loader:
        images, labels = data
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1) #what

        total += labels.size(0)
        correct += (predicted == labels).sum().item()


print(f"Accuracy : {100 * correct / total}%")

Accuracy : 71.5%


In [ ]:
predicted.shape
data[0].shape

torch.Size([16, 3, 32, 32])

In [ ]:
print(outputs.shape,labels.shape)

torch.Size([16, 2]) torch.Size([16])
